lib/social_django/urls.py
"""URLs module"""
from django.conf import settings
from django.conf.urls import url

from social_core.utils import setting_name
from . import views


extra = getattr(settings, setting_name('TRAILING_SLASH'), True) and '/' or ''

app_name = 'social'

urlpatterns = [
    # authentication / association
    url(r'^login/(?P<backend>[^/]+){0}$'.format(extra), views.auth,
        name='begin'),
    url(r'^complete/(?P<backend>[^/]+){0}$'.format(extra), views.complete,
        name='complete'),
    # disconnection
    url(r'^disconnect/(?P<backend>[^/]+){0}$'.format(extra), views.disconnect,
        name='disconnect'),
    url(r'^disconnect/(?P<backend>[^/]+)/(?P<association_id>\d+){0}$'
        .format(extra), views.disconnect, name='disconnect_individual'),
]

travel_planner/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^trips/', include('trips.urls')),
    url(r'^login/', views.login, name='login'),
    url(r'^signout/', views.signout, name='signout'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^settings/', views.settings, name='settings'),
    url(r'^settings/password/', views.password, name='password'),
]

trips/urls.py
from django.conf.urls import url
from . import views as trip_views

app_name = 'trips'
urlpatterns = [
    url(r'^$', trip_views.dashboard, name='dashboard'),
    url(r'^new/', trip_views.add_new_trip, name='new'),
    url(r'^join/', trip_views.join, name='join'),
    url(r'^list/', trip_views.trip_list, name='trip_list'),
    url(r'^details/(?P<trip_id>\d+)/', trip_views.details, name='details'),
]

trips/models.py
from django.conf import settings
from django.db import models


class Trip(models.Model):
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='creator')
    origin = models.IntegerField(null=True, blank=True)
    start_date = models.DateTimeField()
    destination = models.IntegerField(null=True, blank=True)
    finish_date = models.DateTimeField()
    route = models.TextField()  # will serve as list of locations
    num_followers = models.IntegerField(default=0)
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL)


class Location(models.Model):
    name = models.CharField(max_length=300)
    lat = models.DecimalField(null=False, max_digits=10, decimal_places=8)
    long = models.DecimalField(null=False, max_digits=11, decimal_places=8)
    start_date = models.DateTimeField()
    photo_url = models.CharField(max_length=200, blank=True)
    meeting_point = models.CharField(max_length=100, blank=True)
    state = models.CharField(max_length=50, blank=True)
    country = models.CharField(max_length=50, blank=True)
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE)
    parent = models.IntegerField(null=True, blank=True)

trips/forms.py
from django import forms


class NewTripForm(forms.Form):
    origin_input = forms.CharField(max_length=300, strip=True, widget=forms.TextInput(
        attrs={'id': 'origin-input', 'class': 'form-control geocomplete', 'placeholder': 'Enter an origin location'}))
    origin_name = forms.CharField(max_length=200, strip=True, widget=forms.HiddenInput(attrs={'data-geo': 'name'}))
    origin_lat = forms.DecimalField(widget=forms.HiddenInput(attrs={'data-geo': 'lat'}))
    origin_lng = forms.DecimalField(widget=forms.HiddenInput(attrs={'data-geo': 'lng'}))
    origin_state = forms.CharField(max_length=50, strip=True, required=False,
                                   widget=forms.HiddenInput(attrs={'data-geo': 'administrative_area_level_1'}))
    origin_country = forms.CharField(max_length=50, strip=True, required=False,
                                     widget=forms.HiddenInput(attrs={'data-geo': 'country'}))
    start_date = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'], widget=forms.TextInput(
        attrs={'id': 'start_date', 'class': 'form-control', 'placeholder': 'Pick start date & time'}))
    destination_input = forms.CharField(max_length=300, strip=True, widget=forms.TextInput(
        attrs={'id': 'destination-input', 'class': 'form-control geocomplete', 'placeholder': 'Enter an destination location'}))
    destination_name = forms.CharField(max_length=200, strip=True, widget=forms.HiddenInput(attrs={'data-geo': 'name'}))
    destination_lat = forms.DecimalField(widget=forms.HiddenInput(attrs={'data-geo': 'lat'}))
    destination_lng = forms.DecimalField(widget=forms.HiddenInput(attrs={'data-geo': 'lng'}))
    destination_state = forms.CharField(max_length=50, strip=True, required=False,
                                        widget=forms.HiddenInput(attrs={'data-geo': 'administrative_area_level_1'}))
    destination_country = forms.CharField(max_length=50, strip=True, required=False,
                                          widget=forms.HiddenInput(attrs={'data-geo': 'country'}))
    finish_date = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'], widget=forms.TextInput(
        attrs={'id': 'finish_date', 'class': 'form-control', 'placeholder': 'Pick finish date & time'}))
    photo_url = forms.URLField(max_length=200, required=False, widget=forms.URLInput(
        attrs={'id': 'photo_url', 'class': 'form-control', 'placeholder': 'Enter image URL'}))
    meeting_point = forms.CharField(max_length=100, strip=True, required=False, widget=forms.TextInput(
        attrs={'id': 'meeting_point', 'class': 'form-control', 'placeholder': 'Enter a meeting point location'}))

trips/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.http import JsonResponse

from .models import Trip, Location
from .forms import NewTripForm


@login_required
def dashboard(request):
    num_planned_trips = Trip.objects.filter(creator=request.user).count()
    num_joined_trips = Trip.objects.filter(followers=request.user).count()

    data = {'num_planned_trips': num_planned_trips, 'num_joined_trips': num_joined_trips, }
    return render(request, 'trips/dashboard.html', data)


@login_required
def add_new_trip(request):
    if request.method == 'POST':
        form = NewTripForm(request.POST)
        if form.is_valid():
            trip = Trip(creator=request.user, start_date=form.cleaned_data['start_date'],
                        finish_date=form.cleaned_data['finish_date'])
            trip.save()

            origin_location = Location(name=form.cleaned_data['origin_input'])
            origin_location.lat = form.cleaned_data['origin_lat']
            origin_location.long = form.cleaned_data['origin_lng']
            origin_location.state = form.cleaned_data['origin_state']
            origin_location.country = form.cleaned_data['origin_country']
            origin_location.start_date = form.cleaned_data['start_date']
            origin_location.meeting_point = form.cleaned_data['meeting_point']
            origin_location.trip = trip
            origin_location.save()

            trip.origin = origin_location.pk
            trip.start_date = form.cleaned_data['start_date']
            trip.save()

            destination_location = Location(name=form.cleaned_data['destination_input'])
            destination_location.lat = form.cleaned_data['destination_lat']
            destination_location.long = form.cleaned_data['destination_lng']
            destination_location.state = form.cleaned_data['destination_state']
            destination_location.country = form.cleaned_data['destination_country']
            destination_location.start_date = form.cleaned_data['finish_date']
            destination_location.photo_url = form.cleaned_data['photo_url']
            destination_location.trip = trip
            destination_location.parent = origin_location.pk
            destination_location.save()

            trip.destination = destination_location.pk
            trip.finish_date = form.cleaned_data['finish_date']
            list_route = [origin_location.pk, destination_location.pk]
            trip.route = '-'.join(map(str, list_route))
            trip.followers.add(request.user)
            trip.num_followers = 1
            trip.save()

            return HttpResponseRedirect(reverse('trips:details', args=(trip.pk,)))
        else:
            data = {'form': form}
            return render(request, 'trips/new_trip.html', data)
    else:
        data = {'form': NewTripForm()}
    return render(request, 'trips/new_trip.html', data)


@login_required
def trip_list(request):
    trips = Trip.objects.all().order_by('-start_date', '-id')
    locations = Location.objects.all().order_by('-id')

    list_trips = []
    for trip in trips:
        route = trip.route
        if route:
            route = route.split('-')
        else:
            route = []

        origin_name = ''
        destination_name = ''

        start_date = trip.start_date
        start_date = start_date.strftime("%d %B %Y %H:%M")
        finish_date = trip.finish_date
        finish_date = finish_date.strftime("%d %B %Y %H:%M")
        for location in locations:
            if len(route):
                for i in range(len(route)):
                    if int(route[i]) == location.id:
                        route[i] = location.name
                        break

            if trip.origin == location.id:
                origin_name = location.name
            if trip.destination == location.id:
                destination_name = location.name
            if origin_name and destination_name:
                break

        if len(route):
            route = '<br><i class="fa fa-fw fa-arrow-right"></i> '.join(map(str, route))
        else:
            route = ''
        list_trip = {'id': trip.id, 'origin_name': origin_name, 'destination_name': destination_name,
                     'start_date': start_date, 'finish_date': finish_date, 'route': route}
        list_trips.append(list_trip)

    data = {'trips': list_trips}
    return render(request, 'trips/trip_list.html', data)


@login_required
def details(request, trip_id):
    try:
        trip_id = int(trip_id)
    except ValueError:
        trip_id = 0
    locations = Location.objects.filter(trip__pk=trip_id)
    if locations:
        dict_location = {}
        for location in locations:
            dict_location[str(location.id)] = location

        trip = locations[0].trip
        destination_location = dict_location[str(trip.destination)]
        num_followers = trip.num_followers
        origin = trip.origin
        destination = trip.destination
        route = trip.route
        if route:
            route = route.split('-')
        else:
            route = []
        locations_route = []
        for i in route:
            locations_route.append(dict_location[str(i)])

        is_creator = False
        has_joined = False
        if trip.creator == request.user:
            is_creator = True
        already_join = Trip.objects.filter(pk=trip_id, followers=request.user)
        if already_join:
            has_joined = True

        data = {'num_followers': '{:,}'.format(num_followers), 'origin': origin, 'destination': destination,
                'destination_location': destination_location, 'trip_id': trip_id, 'is_creator': is_creator,
                'has_joined': has_joined, 'locations_route': locations_route}
        return render(request, 'trips/details.html', data)
    else:
        raise Http404("Trip does not exist")


def join(request):
    try:
        trip_id = int(request.POST.get('id', ''))
    except ValueError:
        trip_id = 0
    trip = Trip.objects.filter(pk=trip_id)
    if trip:
        already_join = trip.filter(followers=request.user)
        if already_join:
            status = 'ok'
            message = "You've already joined this trip."
        else:
            trip[0].followers.add(request.user)
            num_followers = trip[0].num_followers
            trip[0].num_followers = num_followers + 1
            trip[0].save()

            if trip.filter(followers=request.user):
                status = 'ok'
                message = 'You are now joining this trip.'
            else:
                status = 'error'
                message = 'A database error occured. Please try again.'
    else:
        status = 'error'
        message = 'Specified trip is not found.'
    data = {'status': status, 'message': message}
    return JsonResponse(data)

trips/templates/trips/dashboard.html
{% extends "base.html" %}

{% load static %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<section class="content-header">
	<h1>
		Dashboard
	</h1>
	<ol class="breadcrumb">
		<li><a class="no-ajaxy" href="/"><i class="fa fa-home"></i> Home</a></li>
        <li class="active">Dashboard</li>
	</ol>
</section>
<section class="content">
	<div class="row">
        <div class="col-md-3 col-sm-6 col-xs-12">
			<div class="info-box">
				<span class="info-box-icon bg-orange"><i class="ion ion-ios-location"></i></span>
				<div class="info-box-content">
					<span class="info-box-text">Planned Trips</span>
					<span class="info-box-number">{{ num_planned_trips }}</span>
				</div>
			</div>
		</div>
        <!-- fix for small devices only -->
        <div class="clearfix visible-sm-block"></div>
        <div class="col-md-3 col-sm-6 col-xs-12">
			<div class="info-box">
				<span class="info-box-icon bg-green"><i class="ion ion-map"></i></span>
				<div class="info-box-content">
					<span class="info-box-text">Joined Trips</span>
					<span class="info-box-number">{{ num_joined_trips }}</span>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

trips/templates/trips/details.html
{% extends "base.html" %}

{% load static %}

{% block title %}Trip Details{% endblock %}

{% block content %}
<section class="content-header">
	<h1>
		Trip Details
	</h1>
	<ol class="breadcrumb">
		<li><a class="no-ajaxy" href="/"><i class="fa fa-home"></i> Home</a></li>
		<li><a href="/trips/">Trips</a></li>
		<li class="active">Details</li>
	</ol>
</section>
<section class="content">
	<div class="row">
		<div class="col-md-3" id="location-details">
			<div class="box box-primary">
				<div class="box-body box-profile">
					{% if destination_location.photo_url %}
					<img style="width: 100%;" class="profile-user-img img-responsive img-rounded"
						 src="{{ destination_location.photo_url }}" alt="">
					{% else %}
					<img style="width: 100%;" class="profile-user-img img-responsive img-rounded"
						 src="{% static 'img/no-image-available.jpg' %}" alt="">
					{% endif %}
					<h3 class="profile-username text-center">{{ destination_location.name }}</h3>
					<ul class="list-group list-group-unbordered">
						<li class="list-group-item">
							<b>Followers</b> <a class="pull-right">{{ num_followers }}</a>
						</li>
					</ul>
					{% if is_creator %}
					<button data-trip="{{ trip_id }}"
							class="btn btn-primary btn-block disabled">You created this trip
					</button>
					{% elif has_joined %}
					<button data-trip="{{ trip_id }}"
							class="btn btn-primary btn-block disabled">You've joined this trip
					</button>
					{% else %}
					<button data-trip="{{ trip_id }}" class="btn btn-warning btn-block join-trip" title="Join"><i
							class="fa fa-heart"></i><b> Join</b></button>
					{% endif %}
				</div>
			</div>
			<div class="box box-primary">
				<div class="box-header with-border">
					<h3 class="box-title">Address Details</h3>
				</div>
				<div class="box-body">
					<strong><i class="fa fa-building-o margin-r-5"></i> Name</strong>
					<p class="text-muted">{{ destination_location.name }}</p>
					<hr>
					<strong><i class="fa fa-map-marker margin-r-5"></i> Latitude</strong>
					<p class="text-muted">{{ destination_location.lat }}</p>
					<hr>
					<strong><i class="fa fa-map-marker margin-r-5"></i> Longitude</strong>
					<p class="text-muted">{{ destination_location.long }}</p>
					<hr>
					<strong><i class="fa fa-globe margin-r-5"></i> State</strong>
					<p class="text-muted">{{ destination_location.state }}</p>
					<hr>
					<strong><i class="fa fa-flag-o margin-r-5"></i> Country</strong>
					<p class="text-muted">{{ destination_location.country }}</p>
				</div>
			</div>
		</div>
		<div class="col-md-9">
			<div class="nav-tabs-custom">
				<ul class="nav nav-tabs">
					<li class="active"><a href="#timeline" data-toggle="tab">Timeline</a></li>
					<!--<li><a href="#map" data-toggle="tab">Map</a></li>-->
					<li><a href="#fb-comment" data-toggle="tab">Discussions</a></li>
					<li><a href="#insert-destination" data-toggle="tab">Insert Destination</a></li>
				</ul>
				<div class="tab-content">
					<div class="active tab-pane" id="timeline">
						<ul class="timeline timeline-inverse">
							{% for location in locations_route %}
							<li class="time-label">
								<span class="bg-red">{{location.start_date|date:"d M Y"}}</span>
							</li>
							<li>
								{% if location.id == origin %}
								<i class="fa fa-flag bg-blue"></i>
								{% elif location.id == destination %}
								<i class="fa fa-flag-checkered bg-purple"></i>
								{% else %}
								<i class="fa fa-map-pin bg-yellow"></i>
								{% endif %}
								<div class="timeline-item">
									<span class="time"><i class="fa fa-clock-o"></i>{{ location.start_date|date:" H:i" }}</span>
									<h3 class="timeline-header"><a data-location="{{ location.id }}"
									   class="scrollto location-detail" href="#location-details">{{ location.name }}</a></h3>
									<div class="timeline-body">
										{% if forloop.last %}
										<p>Dismissed at final destination.</p>
										{% else %}
										<strong><i class="fa fa-group margin-r-5"></i> Meeting Point</strong>
										<p>{% if location.meeting_point %}{{ location.meeting_point }}{% else %}-{% endif %}</p>
										{% endif %}
									</div>
									<div class="timeline-footer">
										<a class="btn btn-primary btn-xs">Insert New Destination</a>
										<!--<a class="btn btn-danger btn-xs">Delete</a>-->
									</div>
								</div>
							</li>
							{% endfor %}
							<li>
								<i class="fa fa-clock-o bg-gray"></i>
							</li>
						</ul>
					</div>
					<div class="tab-pane" id="map">
						<div id="controls"></div>
						<div id="gmap" style="with: 100%;height: 600px;"></div>
					</div>
					<div class="tab-pane" id="fb-comment">
						<div class="fb-comments" data-order-by="reverse_time" data-width="100%"></div>
					</div>
					<div class="tab-pane" id="insert-destination">
						<form>
							<div class="box-body">
								<div class="form-group">
									<label for="parent-destination">Insert After</label>
									<select class="form-control" name="parent-destination" id="parent-destination">
										<option>Highfield Interchange</option>
										<option>London Eye</option>
										<option>Buckingham Palace</option>
										<option>Eiffel Tower</option>
									</select>
								</div>
								<div class="form-group">
									<label for="new-destination-input">Destination Location</label>
									<input type="text" class="form-control" id="new-destination-input"
										   placeholder="Enter a new destination location" required>
								</div>
								<div class="form-group">
									<label for="start_date">Start Date</label>
									<div class="input-group" id="datetimepicker_start_date2">
										<input type="text" class="form-control" id="start_date"
											   placeholder="Pick start date & time" required>
										<span class="input-group-addon">
											<i class="fa fa-calendar"></i>
										</span>
									</div>
								</div>
								<div class="form-group">
									<label for="photo_url">Photo URL <code>optional</code></label>
									<div class="input-group">
										<input type="url" class="form-control" id="photo_url"
											   placeholder="Enter image URL">
										<span class="input-group-addon">
											<i class="fa fa-camera"></i>
										</span>
									</div>
									<p class="help-block">Preferably *.jpg, *.png with dimension 1024x768 px</p>
								</div>
								<div class="form-group">
									<label for="meeting_point">Meeting Point <code>optional</code></label>
									<div class="input-group">
										<input type="text" class="form-control" id="meeting_point"
											   placeholder="Enter a meeting point location">
										<span class="input-group-addon">
											<i class="fa fa-group"></i>
										</span>
									</div>
								</div>
							</div>
							<div class="box-footer">
								<button type="submit" class="btn btn-primary">Save</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<div class="modal modal-info fade" id="modal-join" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span></button>
				<h4 id="myModalLabel" class="modal-title">Join Trip</h4>
			</div>
			<div class="modal-body">
				<p class="join-message"></p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-outline pull-right" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block custom_script %}
<script>
	$(function () {
		var datetimepicker_options = {
			format: "DD/MM/YYYY HH:mm",
			showTodayButton: true,
			showClear: true,
			showClose: true,
			allowInputToggle: true,
			keepOpen: false,
			widgetPositioning: {
				horizontal: "left"
			}
		};
		$("#datetimepicker_start_date").datetimepicker(datetimepicker_options);
		$("#datetimepicker_start_date2").datetimepicker(datetimepicker_options);
		$("#datetimepicker_finish_date").datetimepicker(datetimepicker_options);
		
		$("#new-origin-input").geocomplete({});
		$("#new-destination-input").geocomplete()
		.bind("geocode:result", function(event, result){
			<!-- alert(result.formatted_address); -->
		})
		.bind("geocode:geocode:error", function(event, result){
			<!-- alert(result); -->
		});
		
		var LocsAv2 = [
		{
			lat: 45.9,
			lon: 10.9,
			title: 'Zone A1',
			html: '<h3>Content A1</h3>',
			type : 'circle',
			circle_options: {
				radius: 200000
			},
			draggable: true
		},
		{
			lat: 44.8,
			lon: 1.7,
			title: 'Draggable',
			html: '<h3>Content B1</h3>',
			show_infowindow: false,
			visible: true,
			draggable: true
		},
		{
			lat: 51.5,
			lon: -1.1,
			title: 'Title C1',
			html: [
            '<h3>Content C1</h3>',
            '<p>Lorem Ipsum..</p>'
			].join(''),
			zoom: 8,
			visible: true
		}
		];
		new Maplace({
			locations: LocsAv2,
			map_div: '#gmap',
			controls_div: '#controls',
			controls_type: 'list',
			controls_on_map: false,
			view_all_text: 'Start',
			type: 'polyline'
		}).Load();

		// handle for Join button
		$("section.content").on("click", ".join-trip", function(e) {
			var this_selector = $(this);
			$.ajax({
				method: 'POST',
				url: '{% url 'trips:join' %}',
				data: {
					id: $(this).data('trip'),
					csrfmiddlewaretoken: '{{ csrf_token }}'
				},
				dataType: 'json',
				success: function (data) {
					if (data.status !== 'ok') {
						$("#modal-join").removeClass('modal-info').addClass('modal-danger');
					}
					$("#modal-join p.join-message").text(data.message);
					this_selector.removeClass('btn-warning join-trip').addClass('btn-primary disabled');
					this_selector.text(data.message);
				},
				error: function (jqXHR, textStatus, errorThrown) {
					$("#modal-join").removeClass('modal-info').addClass('modal-danger');
					$("#modal-join p.join-message").text(textStatus + ': ' + errorThrown);
				},
				complete: function (jqXHR, textStatus) {
					$('#modal-join').modal({backdrop: 'static'});
				}
			});
			e.preventDefault();
		});
	});


</script>
{% endblock %}

trips/templates/trips/password.html
{% extends 'base.html' %}

{% block content %}
  <h2>Change Password</h2>
  {% if not user.has_usable_password %}
    <p style="color: red">You have not defined a password yet.</p>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save changes</button>
  </form>
{% endblock %}

trips/templates/trips/settings.html
{% extends 'base.html' %}

{% block content %}
  <h2>Settings</h2>

  <h3>Facebook</h3>
  {% if facebook_login %}
    <p>Connected as <a href="https://facebook.com/{{ facebook_login.extra_data.id }}/" target="_blank">{{ facebook_login.extra_data.id }}</a></p>
    {% if can_disconnect %}
      <form method="post" action="{% url 'social:disconnect' 'facebook' %}">
        {% csrf_token %}
        <button type="submit">Disconnect from Facebook</button>
      </form>
    {% else %}
      <button type="button" disabled>Disconnect from Facebook</button>
      <p style="color: red">You must <a href="{% url 'password' %}">define a password</a> for your account before disconnecting from Facebook.</p>
    {% endif %}
  {% else %}
    <a href="{% url 'social:begin' 'facebook' %}">Connect to Facebook</a>
  {% endif %}

{% endblock %}

trips/templates/trips/trip_list.html
{% extends "base.html" %}

{% load static %}

{% block title %}Trip Plans{% endblock %}

{% block content %}
<section class="content-header">
	<h1>Trip Plans</h1>
	<ol class="breadcrumb">
		<li><a class="no-ajaxy" href="/"><i class="fa fa-home"></i> Home</a></li>
		<li><a href="/trips/"><i class="fa fa-dashboard"></i> Dashboard</a></li>
		<li class="active">Trip Plans</li>
	</ol>
</section>
<section class="content">
	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
				</div>
				<div class="box-body table-responsive">
					<table id="trip-list" class="table table-bordered table-striped table-hover">
						<thead>
						<tr>
							<th style="text-align: center;">Origin</th>
							<th style="text-align: center;">Route</th>
							<th style="text-align: center; width: 14%;">Start Date</th>
							<th style="text-align: center; width: 14%;">Finish Date</th>
							<th style="text-align: center; width: 6%;">Action</th>
						</tr>
						</thead>
						<tbody>
						{% for trip in trips %}
						<tr>
							<td>{{ trip.origin_name }}</td>
							<td><i class="fa fa-flag"></i> {% autoescape off %}{{ trip.route }}{% endautoescape %} <i
									class="fa fa-flag-checkered"></i></td>
							<td>{{ trip.start_date }}</td>
							<td>{{ trip.finish_date }}</td>
							<td style="text-align: center;">
								<div class="btn-group-vertical">
									<a href="/trips/details/{{ trip.id }}" class="btn btn-info" title="Detail"><i
											class="fa fa-eye"></i></a>
									<a data-trip="{{ trip.id }}" class="btn btn-warning join-trip"
									   title="Join"><i class="fa fa-heart"></i></a>
								</div>
							</td>
						</tr>
						{% endfor %}
						</tbody>
						<tfoot>
						</tfoot>
					</table>
				</div>
			</div>
		</div>
	</div>
</section>
<div class="modal modal-info fade" id="modal-join" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span></button>
				<h4 id="myModalLabel" class="modal-title">Join Trip</h4>
			</div>
			<div class="modal-body">
				<p class="join-message"></p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-outline pull-right" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block custom_script %}
<script type="text/javascript">
	$(function () {
		$('#trip-list').DataTable({
			'ordering' : false
		});
		
		$(".join-trip").click(function(e) {
			$.ajax({
				method: 'POST',
				url: '{% url 'trips:join' %}',
				data: {
					id: $(this).data('trip'),
					csrfmiddlewaretoken: '{{ csrf_token }}'
				},
				dataType: 'json',
				success: function (data) {
					if (data.status !== 'ok') {
						$("#modal-join").removeClass('modal-info').addClass('modal-danger');
					}
					$("#modal-join p.join-message").text(data.message);
				},
				error: function (jqXHR, textStatus, errorThrown) {
					$("#modal-join").removeClass('modal-info').addClass('modal-danger');
					$("#modal-join p.join-message").text(textStatus + ': ' + errorThrown);
				},
				complete: function (jqXHR, textStatus) {
					$('#modal-join').modal({backdrop: 'static'});
				}
			});
			e.preventDefault();
		});
	});
</script>
{% endblock %}